###

POST http://localhost:3000/api/v1/usuarios HTTP/1.1
content-type: application/json

{
    "nombre" : "Leonelr",
    "email": "test@test.com",
    "password": "1234567",
    "rol": "ADMIN"
}

###

POST http://localhost:3000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "guasimo12@gmail.com",
    "password": "1234567"
}


###

POST http://localhost:3000/api/v1/clientes HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWUyN2U2Ny1lNDVhLTQ2NWQtYWU3Yy02NDNjMGI5N2I1ZDgiLCJpYXQiOjE3NDI3NjM5MjksImV4cCI6MTc0Mjg1MDMyOX0.c9yH4K7Fm5mAtWd88vXmP881Wk7KR2mex1jM4mb0

{
    "nombre": "Leonel",
    "email": "guasimo01@gmail.com",
    "cedula": "8-921-1234",
    "telefono": "67890123",
    "direccion": "Callejon del Gato"
}


###

GET http://localhost:3000/api/v1/clientes HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZWUyN2U2Ny1lNDVhLTQ2NWQtYWU3Yy02NDNjMGI5N2I1ZDgiLCJpYXQiOjE3NDI3NjM5MjksImV4cCI6MTc0Mjg1MDMyOX0.c9yH4K7Fm5mAtWd88vXmP881Wk7KR2mex1jM4mb0


###
GET http://localhost:3000/api/v1/health