###

POST http://localhost:3000/api/v1/usuarios HTTP/1.1
content-type: application/json

{
    "nombre" : "Leonelr",
    "email": "test@test.com",
    "password": "1234567",
    "rol": "ADMIN"
}

###

POST http://localhost:3000/api/v1/auth/login HTTP/1.1
content-type: application/json

{
    "email": "guasimo12@gmail.com",
    "password": "1234567"
}


###

POST http://localhost:3000/clientes HTTP/1.1
content-type: application/json

{
    "nombre": "Leonel",
    "email": "guasimo01@gmail.com",
    "cedula": "8-921-1234",
    "telefono": "67890123",
    "direccion": "Callejon del Gato"
}


###

GET http://localhost:3000/api/v1/clientes HTTP/1.1
Authorization: Bearer {"sddfdfdffdfdfdfd"}


###
GET http://localhost:3000/api/v1/health